channels:
  - ../built-deps
  - qiime2
  - biocore
  - defaults
  - nodefaults

dependencies:
  - python=3.5*
  - setuptools
  - qiime2=2017.3.*
  - scikit-bio
  - pandas
  - biom-format>=2.1.5,<2.2.0
  - ijson
  - h5py
